diff --git a/docker/1.11.0/Dockerfile.cpu b/docker/1.11.0/Dockerfile.cpu
index a303107..9b5db23 100644
--- a/docker/1.11.0/Dockerfile.cpu
+++ b/docker/1.11.0/Dockerfile.cpu
@@ -2,9 +2,9 @@ FROM ubuntu:16.04
 
 LABEL maintainer="Amazon AI"
 
-ARG framework_installable
+ARG framework_installable="tensorflow==1.11"
 ARG framework_support_installable=sagemaker_tensorflow_container-2.0.0.tar.gz
-ARG py_version
+ARG py_version=2
 
 # Validate that arguments are specified
 RUN test $framework_installable || exit 1 \
@@ -51,11 +51,13 @@ ENV KMP_AFFINITY=granularity=fine,compact,1,0 KMP_BLOCKTIME=1 KMP_SETTINGS=0
 
 WORKDIR /
 
-COPY $framework_installable .
+# COPY $framework_installable .
 COPY $framework_support_installable .
 
+RUN pip --no-cache-dir install --upgrade 'pip<20' 'setuptools<50'
 RUN pip install --no-cache-dir -U \
     keras==2.2.4 \
+    scipy==1.2.2 \
     $framework_support_installable \
     "sagemaker-tensorflow>=1.11,<1.12" \
     # Let's install TensorFlow separately in the end to avoid
diff --git a/docker/1.11.0/Dockerfile.gpu b/docker/1.11.0/Dockerfile.gpu
index 92e9859..dea2853 100644
--- a/docker/1.11.0/Dockerfile.gpu
+++ b/docker/1.11.0/Dockerfile.gpu
@@ -2,7 +2,7 @@ FROM nvidia/cuda:9.0-base-ubuntu16.04
 
 LABEL maintainer="Amazon AI"
 
-ARG framework_installable
+ARG framework_installable="tensorflow-gpu==1.11"
 ARG framework_support_installable=sagemaker_tensorflow_container-2.0.0.tar.gz
 ARG py_version
 
@@ -72,11 +72,12 @@ RUN curl -fSsL -O https://bootstrap.pypa.io/get-pip.py && \
 
 WORKDIR /
 
-COPY $framework_installable .
+# COPY $framework_installable .
 COPY $framework_support_installable .
-
+RUN pip --no-cache-dir install --upgrade 'pip<20' 'setuptools<50'
 RUN pip install --no-cache-dir -U \
     keras==2.2.4 \
+    scipy==1.2.2 \
     $framework_support_installable \
     "sagemaker-tensorflow>=1.11,<1.12" \
     # Let's install TensorFlow separately in the end to avoid
