diff --git a/docker/1.13.1/Dockerfile.cpu b/docker/1.13.1/Dockerfile.cpu
index a0d9478..e1ee923 100644
--- a/docker/1.13.1/Dockerfile.cpu
+++ b/docker/1.13.1/Dockerfile.cpu
@@ -58,31 +58,33 @@ ENV KMP_AFFINITY=granularity=fine,compact,1,0 KMP_BLOCKTIME=1 KMP_SETTINGS=0
 WORKDIR /
 
 ARG PYTHON=python3
-ARG PYTHON_PIP=python3-pip
 ARG PIP=pip3
-ARG PYTHON_VERSION=3.6.6
 
-RUN wget https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz && \
-    tar -xvf Python-$PYTHON_VERSION.tgz && cd Python-$PYTHON_VERSION && \
-    ./configure && make && make install && \
-    apt-get update && apt-get install -y --no-install-recommends libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev && \
-    make && make install && rm -rf ../Python-$PYTHON_VERSION* && \
-    ln -s /usr/local/bin/pip3 /usr/bin/pip
+ARG py_version
+
+RUN if [ $py_version -eq 3 ]; then PYTHON_VERSION=python3.6; else PYTHON_VERSION=python2.7; fi && \
+        add-apt-repository ppa:deadsnakes/ppa -y && apt-get update && apt-get install -y --no-install-recommends $PYTHON_VERSION-dev --allow-unauthenticated  && \
+        ln -s -f /usr/bin/$PYTHON_VERSION /usr/bin/python && \
+        ln -s -f /usr/bin/$PYTHON_VERSION /usr/bin/python3 && \
+	rm -rf /var/lib/apt/lists/*
 
 ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PYTHONIOENCODING=UTF-8 LANG=C.UTF-8 LC_ALL=C.UTF-8
 
+RUN curl -fSsL -O https://bootstrap.pypa.io/get-pip.py && \
+    python get-pip.py --disable-pip-version-check --no-cache-dir "pip==18.1" && \
+    rm get-pip.py
+
 ARG framework_support_installable=sagemaker_tensorflow_container-2.0.0.tar.gz
 COPY $framework_support_installable .
 ARG TF_URL="https://tensorflow-aws.s3-us-west-2.amazonaws.com/1.13/AmazonLinux/cpu/latest-patch-latest-patch/tensorflow-1.13.1-cp36-cp36m-linux_x86_64.whl"
 
-RUN ${PIP} --no-cache-dir install --upgrade pip setuptools
-
 # Some TF tools expect a "python" binary
-RUN ln -s $(which ${PYTHON}) /usr/local/bin/python
+# RUN ln -s $(which ${PYTHON}) /usr/local/bin/python
+RUN ${PIP} --no-cache-dir install --upgrade setuptools
 
 RUN ${PIP} install --no-cache-dir -U \
            numpy==1.16.2 \
-           scipy==1.2.1 \
+           scipy==1.2.2 \
            scikit-learn==0.20.3 \
            pandas==0.24.2 \
            Pillow==5.4.1 \
@@ -97,7 +99,8 @@ RUN ${PIP} install --no-cache-dir -U \
     # Let's install TensorFlow separately in the end to avoid
     # the library version to be overwritten
     ${PIP} install --force-reinstall --no-cache-dir -U \
-           ${TF_URL} \
+           ${TF_URL} && \
+    ${PIP} install --force-reinstall --no-cache-dir -U \
            horovod==0.16.4 && \
     ${PIP} install --no-cache-dir -U $framework_support_installable && \
            rm -f $framework_support_installable && \
