diff --git a/docker/1.15.2/py3/Dockerfile.gpu b/docker/1.15.2/py3/Dockerfile.gpu
index 56b5df5..7e9d0b7 100644
--- a/docker/1.15.2/py3/Dockerfile.gpu
+++ b/docker/1.15.2/py3/Dockerfile.gpu
@@ -36,7 +36,7 @@ RUN apt-get update \
     cuda-cusolver-dev-10-0 \
     cuda-cusparse-dev-10-0 \
     curl \
-    libcudnn7=7.5.1.10-1+cuda10.0 \
+    libcudnn7=7.6.5.32-1+cuda10.0 \
     # TensorFlow doesn't require libnccl anymore but Open MPI still depends on it
     libnccl2=2.4.7-1+cuda10.0 \
     libgomp1 \
@@ -143,7 +143,7 @@ RUN pip install --no-cache-dir -U \
     # Let's install TensorFlow separately in the end to avoid
     # the library version to be overwritten
  && pip install --force-reinstall --no-cache-dir -U \
-    ${TF_URL} \
+    tensorflow_gpu==1.15.2 \
  && pip install --no-cache-dir -U \
     awscli
 
